- name: install nginx
  hosts: frontend

  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: start and enable nginx
      service:
        name: nginx
        state: started
        enabled: true