- name: demo on variables
  hosts: frontend
  tasks:
    - name: print the variable
      debug:
        msg: "Hi, I am learning {{ course }} variables, trainer is {{ trainer }}, Duration is {{ duration }}"
  tasks:
    - name: print the variable
      debug:
        msg: "Hi, I am learning {{ course }} variables, trainer is {{ trainer }}, Duration is {{ duration }}"      