- name: demo on variables
  hosts: local  
  connection: local

  vars:
    course: "Ansible"
    trainer: "Sivakumar"
    duration: "150hrs"

  tasks:
  - name: display the variables
    vars:
     course: "Ansible Automation"
     trainer: "Sam"
     duration: "200hrs"

    debug:  
        msg: "Hi, I am learning {{ course }} variables, trainer is {{ trainer }}, Duration is {{ duration }}"