---
- name: demo on prompt
  hosts: localhost
  connection: local

  vars_prompt:
    - name: "username"
      prompt: "Enter the username"
      private: no

    - name: "password"
      prompt: "Enter the password"
      private: yes

  tasks:
    - name: display the prompt values
      debug:
        msg: "username is {{ username }}, password is {{ password }}"