- name: demo on variables
  hosts: localhost
  connection: local

  vars_files:
    - course.yml

  tasks:
    - name: print the variable
      debug:
        msg: "Hi, I am learning {{ course }} variables, trainer is {{ trainer }}, Duration is {{ duration }}"